### ISSUE TITLE
Update go-ipld-prime dependency

### ISSUE THREAD

**Issue by willscott** [filecoin-project/go-data-transfer#202]
This library currently depends on go-ipld-prime v0.5, and due to breaking changes in the interface will not work with versions above v0.7. The current is v0.9.

```
go-data-transfer@v1.4.3/encoding/encoding.go:30:10: undefined: dagcbor.Encoder
go-data-transfer@v1.4.3/encoding/encoding.go:82:9: undefined: dagcbor.Decoder
```

For both of these uses of the codec, all that needs to happen is the final `r` needs to be removed. the functions have become `Encode` and `Decode` respectively.

**Comment by dirkmc** [comment]
Thanks @willscott - is there a pressing need to update go-ipld-prime or is this just a courtesy advisory?

**Comment by willscott** [comment]
downstream users of lotus, including https://github.com/filecoin-project/sentinel-visor, https://github.com/filecoin-project/dealbot, https://github.com/filecoin-project/statediff which make use of ipld-prime are limited to v0.7 until this library can be migrated to the newer interface.

There aren't immediate features any of them need from v0.9, so just a courtesy advisory at this point.
